sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
  - sudo apt-get install graphviz
script:
  - make generated
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf DMTN-073.pdf --upload --lsstdoc DMTN-073.tex --env=travis --ltd-product dmtn-073"
env:
  global:
    # Add encrypted secrets here
    - secure: "vKkgHemmKQVC8lLS4/i7NnKavB3AXAO4rSOq1N3+f4hT5dx90dWziWoZ2LoAqBfDTESeFv4TFqt7eStbbssTXyWFmNR53O2oDJ047tYxzYSLUgxqyCNCE826lfllD2ZEDWV8pBvRasv9tt8dl8p+eRUeH+UGpcL5lVOM/2j3HEZk0TE6aurd89OtCfR0o2JtpHAk3AljP7GAyWcLZtHQD0zMfpk2b4v4NN1IVKdXhaZE740SFORX2ke2vU3mUM+Fzal53HiSX9nrivT89X9qSnrBtA0aZJkz8yN+t2iRytNBZluVAJWB+tJ+D329VZY7In4b6b+lekrqolJ2wCqOs2+87beop6/E2xeHHQf9vSYiX4Mbb/bAVtUHHEW8DliZdC9/0zqXhpCcyubUsXad8cCAC6yQiGIlXoKSYpjNGoqbM+hQ5xhMV4oDGUkfCDZ0DqyyvJbU89/mDnOih24otIOjiKHq4THdVnw6l1v1Wi0gAew/TZBuzp1bTyicnEADMsMTMOSEXbdvmi1HrAt4j43yuivJyQKtklazU7upba7sQEar+LM0Pwpe0FSHL7ZnrXnlXHTQQFZ8Jdl3Sd4u3SXpMvQabzsHQ321rvAEg15OsywKZUGmgLSgzT60pclxYxd4EdY6+0bZyaZ9GjvtJZn3thrVCZqSH2UUs6i4ies="
    - secure: "xlKe0zl+fZyPwuktVG7hkXtnVRQTHfABmz5tCABOVK/nNYg9E+DegITwR213QWMaSNM8HgqSvE4T2aUafYihgSw4NAv+2DjL94tD98nltSTZrjIPcaNSrrafnHMh2/Oa41paH2sQCeW043D0DGn/n1JPWQsHT7/GK5vRLvKW9twkmZG+XnJArkX0+cXXPWxbTzhwu6WKHzbh1CyYK72rwqTvNAyZa+wKC9xmCLFBStFkwzBgjmmd+rt32WJMHNnE8ksL51FXlDG0bif1QkX0lnVbqwEyOxHQ1DZB0iigStxogjU87aSs4uhgNgo2u7jLurs+cuGq0I61EHHm1iVawHtcbMtDiPmnuSPCeADzlJNw/WfLYFYJ8Mb7Q+u0ggZ5J/2h+H47h3kF0KKsVtHAC6gOyZQQJpV/046cFEe/jVaCv1K9x5zFsMhlwzPyPxqCT3v5y0+5tfJvTdQJwIbklOnjjFvys46Mn+RseJcDfwHjIcFZhdaINaxOPR+etJnlhh7n9Mxtz5HFnwZUyhzRbTXdjGYH7iJtKwRhcq6QODbxe2B/J+YOlzBUwK237dnxYh+5fqVLPDhFw1iBKMg4rRf+o4gtGMlDR/PhqZQrKWnPMv/l4xmUIdKoORhLRslfWjiiehi3SE74lbeCEkNYvs74mV08cXcZB29UM8MtxMA="
